# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Abstract Title')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('uid', models.IntegerField(default=main.models.Abstract.generate_uid, primary_key=True, serialize=False, verbose_name='UID')),
                ('author1', models.CharField(blank=True, max_length=100, verbose_name='Author 1')),
                ('author2', models.CharField(blank=True, max_length=100, verbose_name='Author 2')),
                ('document', models.FileField(upload_to='documents/abstracts/')),
                ('status', models.CharField(choices=[('AS', 'Abstract Submitted'), ('AC', 'Abstract Checked')], default='AS', max_length=2)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('document', models.FileField(upload_to='documents/papers/')),
                ('status', models.CharField(choices=[('PS', 'Paper Submitted'), ('PC', 'Paper Checked')], default='PS', max_length=2)),
                ('abstract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Abstract')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(verbose_name='Phone')),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abstract',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.UserProfile'),
        ),
    ]
