# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Abstract Title')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('uid', models.IntegerField(default=main.models.Abstract.generate_uid, primary_key=True, serialize=False, verbose_name='UID')),
                ('document', models.FileField(upload_to='documents/abstracts/')),
                ('review', models.TextField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('ASel', 'Abstract Selected'), ('ARej', 'Abstract Rejected'), ('AMod', 'Acceptable after changes')], max_length=4, null=True)),
                ('status', models.CharField(choices=[('AS', 'Abstract Submitted'), ('AC', 'Abstract Checked')], default='AS', max_length=2)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='College/University Name')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('document', models.FileField(upload_to='documents/papers/')),
                ('review', models.TextField(null=True)),
                ('status', models.CharField(choices=[('PS', 'Paper Submitted'), ('PC', 'Paper Checked')], default='PS', max_length=2)),
                ('verdict', models.CharField(choices=[('PSel', 'Abstract Selected'), ('PRej', 'Abstract Rejected')], max_length=4, null=True)),
                ('abstract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Abstract')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('coauthor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Co-Author')),
                ('phone1', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('phone2', models.BigIntegerField(blank=True, null=True, verbose_name='Alternate Phone')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, null=True, verbose_name='Display Name')),
                ('phone1', models.BigIntegerField(null=True, verbose_name='Phone')),
                ('phone2', models.BigIntegerField(blank=True, null=True, verbose_name='Alternate Phone')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(to='main.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abstract',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ParticipantProfile'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ProfessorProfile'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='staff',
            field=models.ManyToManyField(to='main.StaffProfile'),
        ),
    ]
