# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Abstract Title')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='UID')),
                ('author1', models.CharField(blank=True, max_length=100, verbose_name='Author 1')),
                ('author2', models.CharField(blank=True, max_length=100, verbose_name='Author 2')),
                ('document', models.FileField(upload_to='documents/abstracts/')),
                ('status', models.CharField(choices=[('AS', 'Abstract Submitted'), ('AC', 'Abstract Checked')], default='AS', max_length=2)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Paper Title')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='UID')),
                ('author1', models.CharField(blank=True, max_length=100, verbose_name='Author 1')),
                ('author2', models.CharField(blank=True, max_length=100, verbose_name='Author 2')),
                ('document', models.FileField(upload_to='documents/papers/')),
                ('status', models.CharField(choices=[('AS', 'Abstract Submitted'), ('AC', 'Abstract Checked'), ('PS', 'Paper Submitted'), ('PC', 'Paper Checked')], default='AS', max_length=2)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_professor', models.BooleanField(default=False, verbose_name='Is Professor?')),
                ('phone', models.BigIntegerField(verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
