# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Display Name'),
        ),
    ]
