# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_professor', models.BooleanField(default=False, verbose_name='Is Professor?')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='author1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author 1'),
        ),
        migrations.AddField(
            model_name='paper',
            name='author2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author 2'),
        ),
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('AS', 'Abstract Submitted'), ('AC', 'Abstract Checked'), ('PS', 'Paper Submitted'), ('PC', 'Paper Checked')], default='AS', max_length=2),
        ),
    ]
