# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180903_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
