# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='verdict',
            field=models.CharField(blank=True, choices=[('ASel', 'Abstract Selected'), ('ARej', 'Abstract Rejected'), ('AMod', 'Acceptable after changes')], max_length=4, null=True),
        ),
    ]
