# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180828_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Abstract Title')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted')),
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='UID')),
                ('author1', models.CharField(blank=True, max_length=100, verbose_name='Author 1')),
                ('author2', models.CharField(blank=True, max_length=100, verbose_name='Author 2')),
                ('document', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('AS', 'Abstract Submitted'), ('AC', 'Abstract Checked')], default='AS', max_length=2)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.AlterField(
            model_name='paper',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Submitted'),
        ),
    ]
