# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181224_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['abstract__uid']},
        ),
        migrations.AlterField(
            model_name='abstract',
            name='uid',
            field=models.IntegerField(default=b'generate_uid', primary_key=True, serialize=False, verbose_name=b'UID'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='verdict',
            field=models.CharField(choices=[(b'Paper Selected', b'Paper Selected'), (b'Paper Rejected', b'Paper Rejected')], max_length=14, null=True),
        ),
    ]
