# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180907_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['category']},
        ),
    ]
