# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180911_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='verdict',
            field=models.CharField(choices=[('ASel', 'Abstract Selected'), ('ARej', 'Abstract Rejected'), ('AMod', 'Acceptable after changes')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='verdict',
            field=models.CharField(choices=[('PSel', 'Abstract Selected'), ('PRej', 'Abstract Rejected')], max_length=4, null=True),
        ),
    ]
