# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
