# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190120_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='verdict',
            field=models.CharField(blank=True, choices=[(b'Paper Selected', b'Paper Selected'), (b'Paper Rejected', b'Paper Rejected')], max_length=14, null=True),
        ),
    ]
