# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180918_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='College/University Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone1',
            field=models.BigIntegerField(null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone2',
            field=models.BigIntegerField(null=True, verbose_name='Alternate Phone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.College'),
        ),
    ]
