# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180918_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Alternate Phone'),
        ),
    ]
