# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180918_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_participant',
            field=models.BooleanField(default=True),
        ),
    ]
